### ISSUE TITLE
Significant drop in FPS when running Solid-Fueled Generator LIT v1.9-1.0.13

### ISSUE THREAD

**Issue by BlueSilverXIII** [M4thG33k/LittleInsignificantThings_1.9#3]
ive noticed a major drop in FPS when the Solid-Fueled Generator is running. Other generators on the pack doesn't. it drops from 60fps down to 8fps. it doesnt cause any crash but its just weird.
lemme know if u need anything else.

![2016-05-21_20 51 22](https://cloud.githubusercontent.com/assets/19492894/15451541/95f663c2-1f96-11e6-975d-b6c0891b809f.png)
![2016-05-21_20 51 35](https://cloud.githubusercontent.com/assets/19492894/15451542/95f98d90-1f96-11e6-9f0c-ecf009deaf64.png)

**Comment by M4thG33k** [comment]
Thanks for bringing this to my attention; I'll add it to my to-do list.

Is the FPS drop only when the GUI is open, or when the generator is running in general? Thanks!

**Comment by BlueSilverXIII** [comment]
the fps drop is remains until the machine stops working or im a chunk or 2 away. I just opened the GUI to show it running XD

**Comment by M4thG33k** [comment]
Alright, I think I found the source of this issue. The next update should have a fix. :-)  Sorry for taking so long.
