### ISSUE TITLE
Graves not forming

### ISSUE THREAD

**Issue by TyoAtrosa** [M4thG33k/LittleInsignificantThings_1.9#4]
on the 1.9 version Whenever i die a grave does not form and my inventory scatters all over like vanilla except the items fly farther.

This is my current modpack Setup.

[new Modpack-1.0.zip](https://github.com/M4thG33k/LittleInsignificantThings_1.9/files/309943/new.Modpack-1.0.zip)

**Comment by M4thG33k** [comment]
Check the config files. I've set the 1.9 version to default to not spawn graves because the grave was moved to its own mod: Tomb Many Graves. 

The mod does not affect the way the items drop upon death.

**Comment by TyoAtrosa** [comment]
It was turned on in the configs, but still wasn't spawning graves. i'll try Tomb Many Graves though.

**Comment by M4thG33k** [comment]
Looking back at my code, I completely removed the spawning of graves in 1.9, so this is not a bug. (I hope you've tried/enjoyed Tomb Many Graves though!)

**Comment by TyoAtrosa** [comment]
thanks for the reply. i did try out TMG and it works great, keep up the
good work!
